export const USER_ROLE = {
  CUSTOMER: 'CUSTOMER',
  RESTAURANT_ADMIN: 'RESTAURANT_ADMIN',
};

export const ENTITY_TYPES = {
  USER: 'USER',
  RESTAURANT: 'RESTAURANT',
  CART: 'CART',
  ORDER: 'ORDER',
};

export const ORDER_STATUS = {
  PLACED: 'PLACED',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
};
